A2bigschool/Controllers/CoursesController.cs
using A2bigschool.Models;
using A2bigschool.ViewModels;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace A2bigschool.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public CoursesController()
        {
            _dbContext = new ApplicationDbContext();
        }
        // GET: Courses
        public ActionResult Create()
        {
            var viewModel = new CourseViewModel
            {
                Categories = _dbContext.Categories.ToList()
            };
            return View(viewModel);
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CourseViewModel viewModel)
        {
            if(!ModelState.IsValid)
            {
                viewModel.Categories = _dbContext.Categories.ToList();
                return View("Create", viewModel);
            }
            var course = new Course
            {
                LecturerId = User.Identity.GetUserId(),
                DateTime =viewModel.GetDateTime(),
                CategoryId = viewModel.Category,
                Place = viewModel.Place
            };
            _dbContext.Courses.Add(course); _dbContext.SaveChanges();
            _dbContext.SaveChanges();
                return RedirectToAction("Index", "Home");
        }
    }
}

A2bigschool/Views/Courses/Create.cshtml
@model A2bigschool.ViewModels.CourseViewModel
@using (Html.BeginForm("Create", "Courses"))
{
        <h2>Create</h2>
        <form>
            @Html.AntiForgeryToken()
            <div class="form-group">

                @Html.LabelFor(m => m.Place)
                @Html.TextBoxFor(m => m.Place, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Place)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Date)
                @Html.TextBoxFor(m => m.Date, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Date)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Time)
                @Html.TextBoxFor(m => m.Time, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Time)
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Category)
                @Html.DropDownListFor(m => m.Category,
                   new SelectList(Model.Categories, "Id", "Name"), "", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.Category)
            </div>
            <button type="submit" value="Save" class="btn btn-primary">Save</button>
        </form>
  }
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval");
}